
package smartcampus.ada;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6b21 
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ADAWsDataService", targetNamespace = "http://tempuri.org/", wsdlLocation = "http://webapps.unitn.it/ADA/ADAWS/ADAWSDataProd1.3/ADAWsData.svc?wsdl")
public class ADAWsDataService
    extends Service
{

    private final static URL ADAWSDATASERVICE_WSDL_LOCATION;
    private final static WebServiceException ADAWSDATASERVICE_EXCEPTION;
    private final static QName ADAWSDATASERVICE_QNAME = new QName("http://tempuri.org/", "ADAWsDataService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://webapps.unitn.it/ADA/ADAWS/ADAWSDataProd1.3/ADAWsData.svc?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ADAWSDATASERVICE_WSDL_LOCATION = url;
        ADAWSDATASERVICE_EXCEPTION = e;
    }

    public ADAWsDataService() {
        super(__getWsdlLocation(), ADAWSDATASERVICE_QNAME);
    }

    public ADAWsDataService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ADAWSDATASERVICE_QNAME);
    }

    public ADAWsDataService(URL wsdlLocation) {
        super(wsdlLocation, ADAWSDATASERVICE_QNAME);
    }

    public ADAWsDataService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ADAWSDATASERVICE_QNAME);
    }

    public ADAWsDataService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ADAWsDataService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName);
    }

    /**
     * 
     * @return
     *     returns IADAWsData
     */
    @WebEndpoint(name = "BasicHttpBinding_IADAWsData")
    public IADAWsData getBasicHttpBindingIADAWsData() {
        return super.getPort(new QName("http://tempuri.org/", "BasicHttpBinding_IADAWsData"), IADAWsData.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IADAWsData
     */
    @WebEndpoint(name = "BasicHttpBinding_IADAWsData")
    public IADAWsData getBasicHttpBindingIADAWsData(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "BasicHttpBinding_IADAWsData"), IADAWsData.class, features);
    }

    /**
     * 
     * @return
     *     returns IADAWsData20091229
     */
    @WebEndpoint(name = "BasicHttpBinding_IADAWsData_20091229")
    public IADAWsData20091229 getBasicHttpBindingIADAWsData20091229() {
        return super.getPort(new QName("http://tempuri.org/", "BasicHttpBinding_IADAWsData_20091229"), IADAWsData20091229.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IADAWsData20091229
     */
    @WebEndpoint(name = "BasicHttpBinding_IADAWsData_20091229")
    public IADAWsData20091229 getBasicHttpBindingIADAWsData20091229(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "BasicHttpBinding_IADAWsData_20091229"), IADAWsData20091229.class, features);
    }

    /**
     * 
     * @return
     *     returns IADAWsData20110214
     */
    @WebEndpoint(name = "BasicHttpBinding_IADAWsData_20110214")
    public IADAWsData20110214 getBasicHttpBindingIADAWsData20110214() {
        return super.getPort(new QName("http://tempuri.org/", "BasicHttpBinding_IADAWsData_20110214"), IADAWsData20110214.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IADAWsData20110214
     */
    @WebEndpoint(name = "BasicHttpBinding_IADAWsData_20110214")
    public IADAWsData20110214 getBasicHttpBindingIADAWsData20110214(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "BasicHttpBinding_IADAWsData_20110214"), IADAWsData20110214.class, features);
    }

    /**
     * 
     * @return
     *     returns IADAWsData20120415
     */
    @WebEndpoint(name = "BasicHttpBinding_IADAWsData_20120415")
    public IADAWsData20120415 getBasicHttpBindingIADAWsData20120415() {
        return super.getPort(new QName("http://tempuri.org/", "BasicHttpBinding_IADAWsData_20120415"), IADAWsData20120415.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IADAWsData20120415
     */
    @WebEndpoint(name = "BasicHttpBinding_IADAWsData_20120415")
    public IADAWsData20120415 getBasicHttpBindingIADAWsData20120415(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "BasicHttpBinding_IADAWsData_20120415"), IADAWsData20120415.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ADAWSDATASERVICE_EXCEPTION!= null) {
            throw ADAWSDATASERVICE_EXCEPTION;
        }
        return ADAWSDATASERVICE_WSDL_LOCATION;
    }

}
