
package smartcampus.ada;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6b21 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IADAWsData_20091229", targetNamespace = "http://Data.ADAWs.unitn.it")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IADAWsData20091229 {


    /**
     * 
     * @param nome
     * @param cognome
     * @return
     *     returns smartcampus.ada.ArrayOfPERPersona
     */
    @WebMethod(operationName = "PER_find_cognome_nome_20091229", action = "http://Data.ADAWs.unitn.it/IADAWsData_20091229/PER_find_cognome_nome_20091229")
    @WebResult(name = "PER_find_cognome_nome_20091229Result", targetNamespace = "http://Data.ADAWs.unitn.it")
    @RequestWrapper(localName = "PER_find_cognome_nome_20091229", targetNamespace = "http://Data.ADAWs.unitn.it", className = "smartcampus.ada.PERFindCognomeNome20091229")
    @ResponseWrapper(localName = "PER_find_cognome_nome_20091229Response", targetNamespace = "http://Data.ADAWs.unitn.it", className = "smartcampus.ada.PERFindCognomeNome20091229Response")
    public ArrayOfPERPersona perFindCognomeNome20091229(
        @WebParam(name = "nome", targetNamespace = "http://Data.ADAWs.unitn.it")
        String nome,
        @WebParam(name = "cognome", targetNamespace = "http://Data.ADAWs.unitn.it")
        String cognome);

    /**
     * 
     * @param idAda
     * @return
     *     returns smartcampus.ada.ArrayOfPERPersona
     */
    @WebMethod(operationName = "PER_find_id_ada_20091229", action = "http://Data.ADAWs.unitn.it/IADAWsData_20091229/PER_find_id_ada_20091229")
    @WebResult(name = "PER_find_id_ada_20091229Result", targetNamespace = "http://Data.ADAWs.unitn.it")
    @RequestWrapper(localName = "PER_find_id_ada_20091229", targetNamespace = "http://Data.ADAWs.unitn.it", className = "smartcampus.ada.PERFindIdAda20091229")
    @ResponseWrapper(localName = "PER_find_id_ada_20091229Response", targetNamespace = "http://Data.ADAWs.unitn.it", className = "smartcampus.ada.PERFindIdAda20091229Response")
    public ArrayOfPERPersona perFindIdAda20091229(
        @WebParam(name = "id_ada", targetNamespace = "http://Data.ADAWs.unitn.it")
        String idAda);

    /**
     * 
     * @param idAda
     * @return
     *     returns smartcampus.ada.ArrayOfPERPosizioni20091229
     */
    @WebMethod(operationName = "PER_find_posizioni_id_ada_20091229", action = "http://Data.ADAWs.unitn.it/IADAWsData_20091229/PER_find_posizioni_id_ada_20091229")
    @WebResult(name = "PER_find_posizioni_id_ada_20091229Result", targetNamespace = "http://Data.ADAWs.unitn.it")
    @RequestWrapper(localName = "PER_find_posizioni_id_ada_20091229", targetNamespace = "http://Data.ADAWs.unitn.it", className = "smartcampus.ada.PERFindPosizioniIdAda20091229")
    @ResponseWrapper(localName = "PER_find_posizioni_id_ada_20091229Response", targetNamespace = "http://Data.ADAWs.unitn.it", className = "smartcampus.ada.PERFindPosizioniIdAda20091229Response")
    public ArrayOfPERPosizioni20091229 perFindPosizioniIdAda20091229(
        @WebParam(name = "id_ada", targetNamespace = "http://Data.ADAWs.unitn.it")
        String idAda);

    /**
     * 
     * @param descrizione
     * @param idToa
     * @param dataRiferimento
     * @param idAda
     * @return
     *     returns smartcampus.ada.ArrayOfVOIPEntity
     */
    @WebMethod(operationName = "VOIP_find_entity_20091229", action = "http://Data.ADAWs.unitn.it/IADAWsData_20091229/VOIP_find_entity_20091229")
    @WebResult(name = "VOIP_find_entity_20091229Result", targetNamespace = "http://Data.ADAWs.unitn.it")
    @RequestWrapper(localName = "VOIP_find_entity_20091229", targetNamespace = "http://Data.ADAWs.unitn.it", className = "smartcampus.ada.VOIPFindEntity20091229")
    @ResponseWrapper(localName = "VOIP_find_entity_20091229Response", targetNamespace = "http://Data.ADAWs.unitn.it", className = "smartcampus.ada.VOIPFindEntity20091229Response")
    public ArrayOfVOIPEntity voipFindEntity20091229(
        @WebParam(name = "id_ada", targetNamespace = "http://Data.ADAWs.unitn.it")
        String idAda,
        @WebParam(name = "descrizione", targetNamespace = "http://Data.ADAWs.unitn.it")
        String descrizione,
        @WebParam(name = "data_riferimento", targetNamespace = "http://Data.ADAWs.unitn.it")
        XMLGregorianCalendar dataRiferimento,
        @WebParam(name = "id_toa", targetNamespace = "http://Data.ADAWs.unitn.it")
        String idToa);

    /**
     * 
     * @param dataRiferimento
     * @param idAda
     * @return
     *     returns smartcampus.ada.ArrayOfPERPosizioni20091229
     */
    @WebMethod(operationName = "PER_find_all_posizioni_20091229", action = "http://Data.ADAWs.unitn.it/IADAWsData_20091229/PER_find_all_posizioni_20091229")
    @WebResult(name = "PER_find_all_posizioni_20091229Result", targetNamespace = "http://Data.ADAWs.unitn.it")
    @RequestWrapper(localName = "PER_find_all_posizioni_20091229", targetNamespace = "http://Data.ADAWs.unitn.it", className = "smartcampus.ada.PERFindAllPosizioni20091229")
    @ResponseWrapper(localName = "PER_find_all_posizioni_20091229Response", targetNamespace = "http://Data.ADAWs.unitn.it", className = "smartcampus.ada.PERFindAllPosizioni20091229Response")
    public ArrayOfPERPosizioni20091229 perFindAllPosizioni20091229(
        @WebParam(name = "id_ada", targetNamespace = "http://Data.ADAWs.unitn.it")
        String idAda,
        @WebParam(name = "data_riferimento", targetNamespace = "http://Data.ADAWs.unitn.it")
        XMLGregorianCalendar dataRiferimento);

    /**
     * 
     * @param idAccount
     * @param idAda
     * @return
     *     returns smartcampus.ada.ArrayOfACCOUNTEntityBase
     */
    @WebMethod(operationName = "ACCOUNT_find_id_ada_20091229", action = "http://Data.ADAWs.unitn.it/IADAWsData_20091229/ACCOUNT_find_id_ada_20091229")
    @WebResult(name = "ACCOUNT_find_id_ada_20091229Result", targetNamespace = "http://Data.ADAWs.unitn.it")
    @RequestWrapper(localName = "ACCOUNT_find_id_ada_20091229", targetNamespace = "http://Data.ADAWs.unitn.it", className = "smartcampus.ada.ACCOUNTFindIdAda20091229")
    @ResponseWrapper(localName = "ACCOUNT_find_id_ada_20091229Response", targetNamespace = "http://Data.ADAWs.unitn.it", className = "smartcampus.ada.ACCOUNTFindIdAda20091229Response")
    public ArrayOfACCOUNTEntityBase accountFindIdAda20091229(
        @WebParam(name = "id_ada", targetNamespace = "http://Data.ADAWs.unitn.it")
        String idAda,
        @WebParam(name = "id_account", targetNamespace = "http://Data.ADAWs.unitn.it")
        String idAccount);

    /**
     * 
     * @param idAda
     * @return
     *     returns smartcampus.ada.ArrayOfGOGRelazioneGerarchica
     */
    @WebMethod(operationName = "GOG_gerarchia_sto_20091229", action = "http://Data.ADAWs.unitn.it/IADAWsData_20091229/GOG_gerarchia_sto_20091229")
    @WebResult(name = "GOG_gerarchia_sto_20091229Result", targetNamespace = "http://Data.ADAWs.unitn.it")
    @RequestWrapper(localName = "GOG_gerarchia_sto_20091229", targetNamespace = "http://Data.ADAWs.unitn.it", className = "smartcampus.ada.GOGGerarchiaSto20091229")
    @ResponseWrapper(localName = "GOG_gerarchia_sto_20091229Response", targetNamespace = "http://Data.ADAWs.unitn.it", className = "smartcampus.ada.GOGGerarchiaSto20091229Response")
    public ArrayOfGOGRelazioneGerarchica gogGerarchiaSto20091229(
        @WebParam(name = "id_ada", targetNamespace = "http://Data.ADAWs.unitn.it")
        String idAda);

}
